import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    globals: true,
    env: {
      JWT_SECRET: "test-jwt-secret-for-vitest",
    },
    environment: "node",
    setupFiles: ["./vitest.setup.ts"],
    include: [
      "src/**/__tests__/**/*.test.ts",
      "src/**/__tests__/**/*.test.tsx",
      "src/tests/**/*.test.ts",
      "src/tests/**/*.test.tsx",
      "src/shared/**/*.test.ts",
      "src/shared/**/*.test.tsx",
      "src/features/**/*.test.ts",
      "src/features/**/*.test.tsx",
    ],
    // Component tests use jsdom via @vitest-environment jsdom directive
    coverage: {
      provider: "v8",
      include: [
        "src/features/**/*.ts",
        "src/features/**/*.tsx",
        "src/shared/**/*.ts",
        "src/shared/**/*.tsx",
      ],
      exclude: [
        "**/index.ts",
        "**/*.config.*",
        "**/__tests__/**",
        "**/client.ts",
        "**/assets/**",
        "**/components/HeroSection.tsx",
        "**/components/FeaturedHospitals.tsx",
        "**/components/HowItWorks.tsx",
        "**/components/ServiceCards.tsx",
        "**/components/StatsSection.tsx",
        "**/components/TrustSection.tsx",
        "**/components/Header.tsx",
        "**/components/Footer.tsx",
        "**/components/ThemeToggle.tsx",
        "**/components/Toast.tsx",
        "**/components/AdminToastWrapper.tsx",
        "**/components/ThemeProvider.tsx",
        "**/components/Skeleton.tsx",
        "**/components/ConfirmDialog.tsx",
        "**/components/SuccessCard.tsx",
        "**/components/AppointmentList.tsx",
        "**/components/PatientForm.tsx",
        "**/components/PatientSelector.tsx",
        "**/components/HospitalSearch.tsx",
        "**/components/ScheduleCalendar.tsx",
        "**/components/AdminSidebar.tsx",
        "**/components/AdminHeader.tsx",
        "**/components/DataTable.tsx",
        "**/shared/types/**",
        "**/shared/hooks/**",
        "**/shared/cache.ts",
        "**/shared/db.ts",
        "**/shared/env.ts",
        "**/env.ts",
      ],
      reporter: ["text", "html"],
    },
    testTimeout: 15000,
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      "@generated": path.resolve(__dirname, "./generated"),
    },
  },
});
